### ISSUE TITLE
Readme link is broken.

### ISSUE THREAD

**Issue by tequdev** [XRPL-Labs/Icons-Images-Buttons-Banners#1]
The link itself appears to be valid, but the preview does not seem to be working.
<img width="918" alt="スクリーンショット 2023-01-24 12 28 49" src="https://user-images.githubusercontent.com/69445828/214206543-c77743f6-25f9-428e-a683-1cac73991623.png">

**Comment by WietseWind** [comment]
Looks like the placeholder image generator is down; https://placeholder.com/

**Comment by tequdev** [comment]
`- ! [#3051FC](https://via.placeholder.com/15/3051FC/000000?text=+) `#3051FC` #blue`

https://via.placeholder.com/15/3051FC/000000?text=+

The placeholder link does not appear to be dead.

https://camo.githubusercontent.com/c20a72cf4399061f9f4dca8b0b8ddbd5d23d7ea8075d3b0235c38c5e5a38499c/68747470733a2f2f7669612e706c616365686f6c6465722e636f6d2f31352f3330353146432f3030303030303f746578743d2b

403 error on githubusercontent link when clicking on Markdown link.
It is possible that the problem is on the Github server side.

**Comment by N3TC4T** [comment]
Hi, thanks for letting us know about this 👍 

The Github link doesn't work because the placeholder link is dead, if it works for you it's because of cache.
<img width="1019" alt="image" src="https://user-images.githubusercontent.com/4756161/214261871-f59e4fa0-2860-4804-9ad0-6b1fa5acc89c.png">
